services:
 base:
   image: postgres
   restart: always
   environment:
     POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
   ports:
     - 5432:5432
   volumes:
     - postgres-data:/var/lib/postgresql/data

 adminer:
   image: adminer
   restart: always
   ports:
     - 8080:8080
     
volumes:
 postgres-data: