services:
 users-base:
   image: postgres:16
   restart: always
   environment:
     POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
   ports:
     - 3107:5432
   volumes:
     - users-data:/var/lib/postgresql/data

 adminer:
   image: adminer
   restart: always
   ports:
     - 8080:8080
     
volumes:
 users-data:
